# -*- coding: utf-8 -*-
"""empresa_X2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BMIywnekT_X6zUpp9Xr93WIg9XMDKfqW
"""

import pandas as pd
from pyspark.sql import SparkSession

from pyspark.sql.functions import col

#sesion spark
spark = SparkSession.builder.appName('EmpresaX').getOrCreate()

df = pd.read_excel('empresa_x2.xlsx')

spark_df = spark.createDataFrame(df)

spark_df.show()

#USANDO COLLECT PARA MOSTRAR DATOS
data = spark_df.collect()
for row in data:
    print(row)

#USANDO FILTER PARA VENTAS MAYOR O MENOR QUE
filter_df = spark_df.filter(spark_df['Total Venta'] > 30000)
filter_df.show()

#AGREGANDO COLUMNA
spark_iva = spark_df.withColumn('IVA', col('Total Venta') * 0.21)
spark_iva.show()

#MAP
product_rdd = spark_df.rdd.map(lambda row: row['Producto o Servicio'])
productos = product_rdd.collect()
print(productos)

#USANDO JOIN
print("Lista de Productos:", ", ".join(productos))

#MEJORANDO ESTETICA CON DATAFRAME
products_df = spark.createDataFrame([(product,) for product in productos], ["Productos"])
products_df.show()