# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fsvLYliZo6PfcoIcx9lIClYZc3Tko5hG
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, mean, expr, corr, count, row_number
from pyspark.sql import functions as F
from pyspark.sql.window import Window

spark = SparkSession.builder.master("local[*]").appName("SparkStats").getOrCreate()

data = [
    ("Peru", 50, 3), ("Peru", 60, 4), ("Peru", 55, 2),
    ("Brasil", 70, 5), ("Brasil", 65, 4), ("Brasil", 60, 3),
    ("España", 80, 4), ("España", 75, 3), ("España", 85, 5),
    ("Peru", 58, 4), ("Brasil", 72, 3), ("España", 78, 2)
]
columns = ["País", "Trabajadores", "Satisfacción"]
df = spark.createDataFrame(data, columns)
df.show()

media_df = df.groupBy("País").agg(mean("Trabajadores").alias("Media_Trabajadores"))
media_df.show()

window = Window.partitionBy("País").orderBy("Trabajadores")
df = df.withColumn("Row", row_number().over(window))

country_counts = df.groupBy("País").count()
df = df.join(country_counts, on="País").withColumn("Mediana_Pos", expr("FLOOR(count / 2) + 1"))

df_median = df.filter(df.Row == df.Mediana_Pos).select("País", "Trabajadores").alias("Mediana_Trabajadores")
df_median.show()

mode_df = df.groupBy("País", "Trabajadores").count().orderBy("País", "count", ascending=False)
mode_df = mode_df.groupBy("País").agg(F.first("Trabajadores").alias("Moda_Trabajadores"))
mode_df.show()

correlation = df.stat.corr("Trabajadores", "Satisfacción")
print("Correlación entre Trabajadores y Satisfacción:", correlation)